feat(components): further improvement layout sidebar component #INFR-4327
worktile/tethys-libs pull request #17
Opened 2022-08-24 07:52 UTC by huanhuanwa

2022-08-24 07:59 UTC, why520crazy requested changes

2022-08-24 07:59 UTC, why520crazy commented on packages/components/src/utils/filter-empty-route-path.ts
> +export const MenusMap: Map<string, Route & { groupMenu: Route }> = new Map();
这个使用驼峰命名法，不是 Pascal

2022-08-24 07:59 UTC, why520crazy commented on tsconfig.json
> +    "strictTemplates": false
这个为啥从严格模式改为 false 呢？我建议还是保持严格模式

2022-08-24 08:01 UTC, why520crazy requested changes

2022-08-24 08:01 UTC, why520crazy commented on packages/components/src/layout/sidebar/sidebar.component.ts
> +        // 初始化的时候，根据T hyGlobalStore 的 activeMenu 获取 menuGroup 的路由，设置高亮状态
T hyGlobalStore 多加了一个空格

2022-08-24 08:13 UTC, huanhuanwa commented on tsconfig.json
> +    "strictTemplates": false
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/44698191/186366324-3f53c345-1659-4f3a-a375-05ca11ca9f3d.png">
指令方式弹出 popover 的时候，传入的 thyConfig 我理解的是不用传 origin 的，设置 strictTemplates 为 true 这里编译会报错。

2022-08-25 07:26 UTC, why520crazy approved these changes

2022-08-25 07:26 UTC, merged